### ISSUE TITLE
Where is the origin?

### ISSUE THREAD

**Issue by domdavis** [Gadgetoid/wallpaper#23]
I'm assuming `0`,`0` is bottom left, but it would appear this may not be the case based on feedback from [twitter](https://twitter.com/Gadgetoid/status/957977637762330629). Could be worth mentioning where the origin is in the `README` and if it's not bottom left, where all sane origins are, then perhaps it should be.

If the origin _is_ bottom left then this issue becomes "the Fingerprint images are incorrectly named", although I'm fairly sure that's not the case...

**Comment by electric-blue-green** [comment]
`0, 0` is the top left as far as I'm aware

**Comment by domdavis** [comment]
But only a madman would use that as the origin... then again, we are talking about @Gadgetoid. Phil, are you able to confirm so I can get my annoying fingerprint smudge working correctly :)

**Comment by electric-blue-green** [comment]
It makes slightly more sense on a monitor for top left, and I know for a fact Apple addresses pixels this way. And since my "Don't Panic" tile is `04, 02` and is in the top left, I'd go for that
![img_5401](https://user-images.githubusercontent.com/18347932/35514706-fcd59c6c-04fe-11e8-8fca-31a8de92824f.JPG)

**Comment by domdavis** [comment]
Good God, it goes as far as Apple? When will the madness end?! I have raised a PR to note the origin in the README and tweaked my files. I shall now go sulk on a corner and mutter about the proper location for `0`, `0` quietly to myself.
